name: "Build"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  varshudo:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-java@v4
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: |
          flutter pub get
          flutter test
          fluter build apk
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


  

