name: "Build"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
      - 'release/*'

#       KEY_PASSWORD=varsha
# KEYSTORE_PASSWORD=varsha
# KEY_ALIAS=upload
# KEYSTORE_FILE="base64"

env:
  KEY_PASSWORD:  ${{ secrets.KEY_PASSWORD }}
  KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS:  ${{ secrets.KEY_ALIAS }}
  STORE_FILE: ${{ runner.temp }}/my_production.jks

jobs:
  varshudo:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
  
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - name: gettting deps
        run: flutter pub get
          
      - name: running test
        run: flutter test

      
      # - name: Create the Keystore
      #   env:
      #     KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      #   run: |
      #     # import keystore from secrets
      #     echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore
 
      - name: Create the JKS
        env:
          JKS_BASE64: ${{ secrets.KEYSTORE_FILE }}
        run: |
          # Decode the Base64 string to JKS
          echo ${{ env.STORE_FILE }}
          touch ${{ env.STORE_FILE }}
          echo $JKS_BASE64 | base64 -d > ${{ env.STORE_FILE }}

      - name: Build APK
        run: |
          flutter build apk

      - name: Build App Bundle
        if: startsWith(github.ref, 'refs/heads/release/')
        run: flutter build appbundle

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


  

